GET http://localhost:3001/api/entries/


###

POST http://localhost:3001/api/entries HTTP/1.1
content-type: application/json

{"name": "pham13123",
"number": "131234"}


###
DELETE http://localhost:3001/api/entries/3 HTTP/1.1